name: mar
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.0.5
  modal_progress_hud: ^0.1.3
  firebase_auth: ^0.16.0
  curved_navigation_bar:
  dio: ^3.0.10
  email_validator: ^1.0.4
  equatable: ^1.2.5
  flip_card: ^0.4.4
  flutter_launcher_icons: ^0.7.1
  flutter_markdown: ^0.5.1
  flutter_svg: ^0.19.2+1
  http:
  image_cropper: ^1.2.0
  image_picker: ^0.6.3+1
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.7+3
  mongo_dart:
  toast:
  charts_flutter: ^0.9.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.5.1
  fluttertoast:
  bottom_navy_bar: ^5.5.0
  flutter_text_to_speech:
  introduction_screen:


  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/
    - images/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
